language: node_js
dist: xenial
node_js:
  - "7"
cache: npm
git:
  depth: false
addons:
  sonarcloud:
    organization: peio42-github
install:
  - npm install
script:
  - npm test
  - sh sonar-project-update-props.sh && sonar-scanner
  
